# Unified Workflow Configuration

# Mode preferences for different document types
mode_preferences:
  policy_document: dynamic
  checklist: static
  audit_report: dynamic
  technical_specification: dynamic
  general_document: static

# Fallback strategy when primary mode produces low confidence results
fallback_strategy: static  # Options: static, dynamic, alternate

# Confidence threshold for triggering fallback (0.0 to 1.0)
confidence_threshold: 0.7

# Logging configuration
logging:
  level: INFO
  file: workflow.log
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Performance settings
performance:
  max_parallel_processes: 4
  timeout_seconds: 300
  retry_attempts: 3

# Output configuration
output:
  format: json
  include_metadata: true
  include_confidence_scores: true
  include_mode_used: true 